CREATE TABLE sales (
    coin TEXT NOT NULL,
    amount INTEGER NOT NULL
);

INSERT INTO sales (coin, amount) VALUES
('AGK', 13),
('GOL', 21),
('KLA', 15),
('AGK', 18);


-- PARA OBTENER TODAS LAS VENTAS DE LA MONEDA 'AGK' 
SELECT * FROM sales
WHERE coin = 'AGK';


-- PARA OBTENER TODOS LOS REGISTROS DE LA TABLA DE VENTAS CON UN MONTO MENOR O IGUAL A 20
SELECT * FROM sales
WHERE amount >= 20;

DROP TABLE sales;